version: '3.4'

services:
  lazztech.obsidianpresenses.vision.microservice.cli:
    image: lazztechobsidianpresensevisionmicroservicecli
    build:
      context: .
      dockerfile: Lazztech.ObsidianPresenses.Vision.Microservice.Cli/Dockerfile

  lazztech.obsidianpresenses.vision.microservice.webapi:
    image: lazztechobsidianpresensevisionmicroservicewebapi
    build:
      context: .
      dockerfile: Lazztech.ObsidianPresenses.Vision.Microservice.Webapi/Dockerfile

