version: '3.4'

services:
#  lazztech.ObsidianPresences.vision.microservice.cli:
#    image: lazztechobsidianpresensevisionmicroservicecli
#    volumes:
##      - /Users/gianlazzarini/Desktop/face_recognition:/face/
##      - C:\Users\Gian Lazzarini\Desktop\face_recognition:/face/
##      - C:\face_recognition:/face/
#      - lazztech-cloud-data:/face/
#    build:
#      context: .
#      dockerfile: Lazztech.ObsidianPresences.Vision.Microservice.Cli/Dockerfile

  # lazztech.obsidianpresences.cloudwebapp:
  #   image: lazztechobsidianpresencescloudwebapp
  #   ports: 
  #     - 80:80
  #   depends_on:
  #     - lazztech.obsidianpresences.vision.microservice.webapi
  #   build:
  #     context: .
  #     dockerfile: Lazztech.ObsidianPresences.CloudWebApp/Dockerfile

  lazztech.obsidianpresences.clientfacade:
    image: lazztechobsidianpresencesclientfacade
    volumes:
#      - /Users/gianlazzarini/Desktop/face_recognition:/face/
#      - C:\Users\Gian Lazzarini\Desktop\face_recognition:/face/
#      - C:\face_recognition:/face/
      - lazztech-cloud-data:/face/
    ports: 
      - 80:80
    build:
      context: .
      dockerfile: Lazztech.ObsidianPresences.ClientFacade/Dockerfile

volumes:
  lazztech-cloud-data: