version: '3.4'

services:
  lazztech.obsidianpresences.cloudwebapp:
    image: gianlazzarini/lazztechobsidianpresencescloudwebapp:arm32
    ports:
      - 80:80
    depends_on:
      - lazztech.obsidianpresences.vision.microservice.webapi
    build:
      context: .
      dockerfile: Lazztech.ObsidianPresences.CloudWebApp/Dockerfile.Rpi

  lazztech.obsidianpresences.vision.microservice.webapi:
    image: gianlazzarini/lazztechobsidianpresensevisionmicroservicewebapi:arm32
    volumes:
      - lazztech-cloud-data:/face/
    ports:
#      - 5000:5000
#      - 5001:5001
#      - 6000:44399
#      - 6001:50660
      - 8080:80
      - 8081:50199
      - 5000:5000
    build:
      context: .
      dockerfile: Lazztech.ObsidianPresences.Vision.Microservice.Webapi/Dockerfile.Rpi

volumes:
  lazztech-cloud-data:
