version: '3.4'

services:
  lazztechcloudclientfacade:
    image: gianlazzarini/lazztechcloudclientfacade:arm32
    depends_on:
      - postgres_image
    volumes:
      - lazztech-vision-data:/face/
      - lazztech-cloud-data:/lazztech_data/
    ports: 
      - 80:80
    build:
      context: .
      dockerfile: Lazztech.Cloud.ClientFacade/Dockerfile.Rpi

  redis_db:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  postgres_image:
    image: postgres:alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: "dbuser"
      POSTGRES_PASSWORD: "dbpwd"
      POSTGRES_DB: "values_db"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  redis-data:
  postgres-data:
  lazztech-vision-data:
  lazztech-cloud-data: