version: '3.4'

services:
  lazztech.obsidianpresenses.vision.microservice.cli:
    image: lazztechobsidianpresensevisionmicroservicecli
    volumes:
      - /Users/gianlazzarini/Desktop/face_recognition:/face/
    build:
      context: .
      dockerfile: Lazztech.ObsidianPresenses.Vision.Microservice.Cli/Dockerfile

