version: '3.4'

services:
  lazztech.ObsidianPresences.vision.microservice.cli:
    image: lazztechobsidianpresensevisionmicroservicecli
    volumes:
      - /Users/gianlazzarini/Desktop/face_recognition:/face/
    build:
      context: .
      dockerfile: Lazztech.ObsidianPresences.Vision.Microservice.Cli/Dockerfile


  lazztech.obsidianpresences.cloudwebapp:
    image: lazztechobsidianpresences
    build:
      context: .
      dockerfile: Lazztech.ObsidianPresences.CloudWebApp/Dockerfile

