version: '3.4'

services:
  lazztech-obsidianpresences-cloudwebapp:
    image: gianlazzarini/lazztechobsidianpresencescloudwebapp:arm32
    ports:
      - 80:80
    depends_on:
      - lazztech-obsidianpresences-vision--webapi
    build:
      context: .
      dockerfile: Lazztech.ObsidianPresences.CloudWebApp/Dockerfile.Rpi

  lazztech-obsidianpresences-vision--webapi:
    image: gianlazzarini/lazztechobsidianpresensevisionmicroservicewebapi:arm32
    volumes:
      - lazztech-cloud-data:/face/
#    ports:
#      - 5000:5000
#      - 5001:5001
#      - 6000:44399
#      - 6001:50660
#      - 8080:80
#      - 8081:50199
#      - 5000:5000
    build:
      context: .
      dockerfile: Lazztech.ObsidianPresences.Vision.Microservice.Webapi/Dockerfile.Rpi

  lazztech.obsidianpresences.clientfacade:
    image: lazztechobsidianpresencesclientfacade
    volumes:
#      - /Users/gianlazzarini/Desktop/face_recognition:/face/
#      - C:\Users\Gian Lazzarini\Desktop\face_recognition:/face/
#      - C:\face_recognition:/face/
      - lazztech-cloud-data:/face/
    environment:
      DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=values_db;username=dbuser;password=dbpwd"
    ports: 
      - 80:80
    build:
      context: .
      dockerfile: Lazztech.ObsidianPresences.ClientFacade/Dockerfile.Rpi

  postgres_image:
    image: postgres:alpine
#    ports:
#      - "5432:5432"
    environment:
      POSTGRES_USER: "dbuser"
      POSTGRES_PASSWORD: "dbpwd"
      POSTGRES_DB: "values_db"

volumes:
  lazztech-cloud-data:
