version: '3.4'

services:
  lazztechcloudclientfacade:
    image: lazztechcloudclientfacade
    depends_on:
      - postgres_image
    volumes:
     - C:\face_recognition:/face/
     - ~\AppData\Roaming\Microsoft\UserSecrets\F0D117F3-0EC4-4600-8843-FDB198DDFBBC:/root/.microsoft/usersecrets/F0D117F3-0EC4-4600-8843-FDB198DDFBBC
     - lazztech-cloud-data:/lazztech_data/
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    ports: 
      - 80:80
    build:
      context: .
      dockerfile: Lazztech.Cloud.ClientFacade/Dockerfile

  redis_db:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  postgres_image:
    image: postgres:alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: "dbuser"
      POSTGRES_PASSWORD: "dbpwd"
      POSTGRES_DB: "values_db"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  redis-data:
  postgres-data:
  lazztech-vision-data:
  lazztech-cloud-data: