version: '3.4'

services:
  lazztechcloudclientfacade:
    image: lazztechcloudclientfacade
    volumes:
#      - /Users/gianlazzarini/Desktop/face_recognition:/face/
#      - C:\Users\Gian Lazzarini\Desktop\face_recognition:/face/
     - C:\face_recognition:/face/
     - ~\AppData\Roaming\Microsoft\UserSecrets\F0D117F3-0EC4-4600-8843-FDB198DDFBBC:/root/.microsoft/usersecrets/F0D117F3-0EC4-4600-8843-FDB198DDFBBC
      # - lazztech-cloud-data:/face/
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    ports: 
      - 80:80
    build:
      context: .
      dockerfile: Lazztech.Cloud.ClientFacade/Dockerfile

  postgres_image:
    image: postgres:alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "dbuser"
      POSTGRES_PASSWORD: "dbpwd"
      POSTGRES_DB: "values_db"

# volumes:
#   lazztech-cloud-data: