version: '3.4'

services:
  lazztechcloudclientfacade:
    image: lazztechcloudclientfacade
    volumes:
#      - /Users/gianlazzarini/Desktop/face_recognition:/face/
#      - C:\Users\Gian Lazzarini\Desktop\face_recognition:/face/
#      - C:\face_recognition:/face/
      - lazztech-cloud-data:/face/
#    environment:
    ports: 
      - 80:80
    build:
      context: .
      dockerfile: Lazztech.Cloud.ClientFacade/Dockerfile

  postgres_image:
    image: postgres:alpine
#    ports:
#      - "5432:5432"
    environment:
      POSTGRES_USER: "dbuser"
      POSTGRES_PASSWORD: "dbpwd"
      POSTGRES_DB: "values_db"

volumes:
  lazztech-cloud-data: