version: '3.4'

services:
  lazztech.ObsidianPresences.vision.microservice.cli:
    image: lazztechobsidianpresensevisionmicroservicecli
    volumes:
#      - /Users/gianlazzarini/Desktop/face_recognition:/face/
#      - C:\Users\Gian Lazzarini\Desktop\face_recognition:/face/
      - C:\face_recognition:/face/
    build:
      context: .
      dockerfile: Lazztech.ObsidianPresences.Vision.Microservice.Cli/Dockerfile


  lazztech.obsidianpresences.cloudwebapp:
    image: lazztechobsidianpresencescloudwebapp
    volumes:
#      - /Users/gianlazzarini/Desktop/face_recognition:/face/
#      - C:\Users\Gian Lazzarini\Desktop\face_recognition:/face/
      - C:\face_recognition:/face/
    ports: 
      - 5000:5000
    build:
      context: .
      dockerfile: Lazztech.ObsidianPresences.CloudWebApp/Dockerfile

